[package]
name = "pose"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
poise = "0.3"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
sqlite = "0.27"
